# assumes use of the following UPS:
# EATON 5E 650i
# Bus 001 Device 003: ID 0463:ffff MGE UPS Systems UPS

- name: Install NUT
  ansible.builtin.apt:
    name: nut

- name: Set up usbhid quirks
  ansible.builtin.copy:
    dest: /etc/modprobe.d/usbhid.conf
    src: usbhid.conf
    mode: "755"

- name: Insert EATON UPS entry
  ansible.builtin.blockinfile:
    path: /etc/nut/ups.conf
    block: |
      # EATON 5E 650i
      # Bus 001 Device 003: ID 0463:ffff MGE UPS Systems UPS
      [eaton]
        driver = usbhid-ups
        port = auto

- name: upsd mode
  ansible.builtin.blockinfile:
    path: /etc/nut/nut.conf
    block: |
      MODE=netserver

- name: Enable nut-driver-enumerator.service
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: nut-driver-enumerator.service

- name: Enable nut-driver.target
  ansible.builtin.systemd:
    enabled: true
    name: nut-driver.target

- name: Enable nut.target
  ansible.builtin.systemd:
    enabled: true
    name: nut.target

- name: Restart nut-server
  ansible.builtin.systemd:
    name: nut-server.service
    state: restarted

- name: Verify UPS is visible
  ansible.builtin.command: upsc eaton

# TODO setup users?
