(setq bozo-required-packages '(auto-complete
                               color-theme
                               zenburn-theme
                               yasnippet
                               yaml-mode
                               sr-speedbar
                               rainbow-mode
                               rainbow-delimiters
                               paredit
                               multi-term
                               hl-line+
                               org
                               offlineimap
                               magit
                               fill-column-indicator
                               move-text
                               ack-and-a-half
                               auto-complete-nxml
                               ac-dabbrev
                               yaml-mode
                               zeitgeist
                               erlang
                               lua-mode
                               protobuf-mode
                               ggtags
                               back-button
                               visible-mark
                               undo-tree
                               jedi
                               eproject))
